# Generated by Django 4.1.1 on 2023-03-11 20:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredproducut',
            name='xpiration_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 13, 20, 59, 52, 802562, tzinfo=datetime.timezone.utc)),
        ),
    ]
